# Generated by Django 4.2.1 on 2023-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('img1', models.ImageField(upload_to='travo1')),
                ('descr', models.TextField()),
            ],
        ),
    ]
